package forge.server;

import java.util.Map;
import forge.MulliganDefs;
import org.testng.Assert;
import org.testng.annotations.Test;

public class ServerConfigTest {
    @Test public void defaults() {
        ServerConfig c = ServerConfig.from(Map.of());
        Assert.assertEquals(c.mode(), ServerConfig.Mode.COMMANDER);
        Assert.assertEquals(c.maxPlayers(), 4);
        Assert.assertEquals(c.startDelaySeconds(), 10);
        Assert.assertEquals(c.reconnectSeconds(), 300);
        Assert.assertEquals(c.afkTimeoutMinutes(), 5);
        Assert.assertEquals(c.rules().gamesPerMatch(), 3);
        Assert.assertTrue(c.rules().enforceDeckLegality());
        Assert.assertTrue(c.allowedPlayers().isEmpty());
        Assert.assertEquals(c.loginFailureLimit(), 5);
        Assert.assertEquals(c.loginFailureWindowSeconds(), 60);
        Assert.assertEquals(c.loginBlockSeconds(), 900);
        Assert.assertEquals(c.crashReportMaxFiles(), 10);
        Assert.assertEquals(c.mulliganRule(), MulliganDefs.MulliganRule.London);
    }
    @Test public void constructedUsesNormalRoomCapacity() {
        Assert.assertEquals(ServerConfig.from(Map.of("FORGE_SERVER_MODE", "CONSTRUCTED")).maxPlayers(), 4);
    }
    @Test public void supportsAllConfiguredFormatsAndVariants() {
        ServerConfig c = ServerConfig.from(Map.of(
                "FORGE_SERVER_MODE", "tiny_leaders",
                "FORGE_SERVER_MAX_PLAYERS", "8",
                "FORGE_SERVER_VARIANTS", "planechase, vanguard, archenemy",
                "FORGE_SERVER_GAMES_PER_MATCH", "5",
                "FORGE_SERVER_COMMANDER_BRACKET", "3",
                "FORGE_SERVER_ENFORCE_DECK_LEGALITY", "false",
                "FORGE_SERVER_MULLIGAN_RULE", "vancouver"));
        Assert.assertEquals(c.mode(), ServerConfig.Mode.TINY_LEADERS);
        Assert.assertEquals(c.maxPlayers(), 8);
        Assert.assertEquals(c.variants(), java.util.Set.of(ServerConfig.Variant.PLANECHASE,
                ServerConfig.Variant.VANGUARD, ServerConfig.Variant.ARCHENEMY));
        Assert.assertEquals(c.rules().gamesPerMatch(), 5);
        Assert.assertEquals(c.rules().commanderBracket(), 3);
        Assert.assertFalse(c.rules().enforceDeckLegality());
        Assert.assertEquals(c.mulliganRule(), MulliganDefs.MulliganRule.Vancouver);
    }
    @Test public void supportsAutoGeneratedModesAndAdminConfiguration() {
        ServerConfig c = ServerConfig.from(Map.of("FORGE_SERVER_MODE", "momir_basic",
                "FORGE_SERVER_ADMIN_TOKEN", "long-random-secret", "FORGE_SERVER_ADMIN_PORT", "9090"));
        Assert.assertEquals(c.mode(), ServerConfig.Mode.MOMIR_BASIC);
        Assert.assertTrue(c.adminEnabled());
        Assert.assertEquals(c.adminPort(), 9090);
    }
    @Test public void supportsOptionalCaseInsensitivePlayerAllowlist() {
        ServerConfig publicRoom = ServerConfig.from(Map.of());
        Assert.assertTrue(publicRoom.allowsPlayer("Anyone"));

        ServerConfig privateRoom = ServerConfig.from(Map.of(
                "FORGE_SERVER_ALLOWED_PLAYERS", "Alice, BOB ",
                "FORGE_SERVER_LOGIN_FAILURE_LIMIT", "3",
                "FORGE_SERVER_LOGIN_FAILURE_WINDOW_SECONDS", "30",
                "FORGE_SERVER_LOGIN_BLOCK_SECONDS", "120"));
        Assert.assertTrue(privateRoom.allowsPlayer("alice"));
        Assert.assertTrue(privateRoom.allowsPlayer("Bob"));
        Assert.assertFalse(privateRoom.allowsPlayer("Carol"));
        Assert.assertEquals(privateRoom.loginFailureLimit(), 3);
        Assert.assertEquals(privateRoom.loginFailureWindowSeconds(), 30);
        Assert.assertEquals(privateRoom.loginBlockSeconds(), 120);
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsBlankAllowedPlayer() {
        ServerConfig.from(Map.of("FORGE_SERVER_ALLOWED_PLAYERS", "Alice,,Bob"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsDuplicateAllowedPlayer() {
        ServerConfig.from(Map.of("FORGE_SERVER_ALLOWED_PLAYERS", "Alice,alice"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsInvalidLoginFailureLimit() {
        ServerConfig.from(Map.of("FORGE_SERVER_LOGIN_FAILURE_LIMIT", "0"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsUnknownVariant() {
        ServerConfig.from(Map.of("FORGE_SERVER_VARIANTS", "PLANECHASE,UNKNOWN"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsDuplicateVariant() {
        ServerConfig.from(Map.of("FORGE_SERVER_VARIANTS", "PLANECHASE,PLANECHASE"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsBadPort() {
        ServerConfig.from(Map.of("FORGE_SERVER_PORT", "0"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsZeroDeadline() {
        ServerConfig.from(Map.of("FORGE_SERVER_RECONNECT_SECONDS", "0"));
    }
    @Test public void supportsDisabledAfkTimeout() {
        Assert.assertEquals(ServerConfig.from(Map.of("FORGE_SERVER_AFK_TIMEOUT", "0")).afkTimeoutMinutes(), 0);
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsAfkTimeoutOverOneHour() {
        ServerConfig.from(Map.of("FORGE_SERVER_AFK_TIMEOUT", "61"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsConflictingArchenemyVariants() {
        ServerConfig.from(Map.of("FORGE_SERVER_VARIANTS", "ARCHENEMY,ARCHENEMY_RUMBLE"));
    }
    @Test public void rejectsAutoGeneratedModesWithDeckSectionVariants() {
        for (String mode : new String[] {"MOMIR_BASIC", "MOJHOSTO"}) {
            for (String variant : new String[] {"PLANECHASE", "ARCHENEMY", "ARCHENEMY_RUMBLE", "VANGUARD"}) {
                Assert.expectThrows(IllegalArgumentException.class,
                        () -> ServerConfig.from(Map.of("FORGE_SERVER_MODE", mode, "FORGE_SERVER_VARIANTS", variant)));
            }
        }
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsAdminPortCollision() {
        ServerConfig.from(Map.of("FORGE_SERVER_PORT", "8080", "FORGE_SERVER_ADMIN_TOKEN", "secret"));
    }
    @Test(expectedExceptions = IllegalArgumentException.class) public void rejectsUnknownMulliganRule() {
        ServerConfig.from(Map.of("FORGE_SERVER_MULLIGAN_RULE", "Modern"));
    }
}
